 Crear tarjeta
POST http://127.0.0.1:3001/cards
Authorization: Basic YWRtaW46YWRtaW4xMjM0
Content-Type: application/json

{
  "cardNumber": "1234567890123456",
  "cardHolder": "John Doe",
  "expirationDate": "12/25",
  "cvv": "123",
  "email": "john.doe@example.com"
}


### Obtener tarjetas por email
GET http://127.0.0.1:3001/cards/john.doe@example.com
Authorization: Basic YWRtaW46YWRtaW4xMjM0
# Actualizar tarjeta
PUT http://127.0.0.1:3001/cards/1234567890123456
Authorization: Basic YWRtaW46YWRtaW4xMjM0
Content-Type: application/json

{
  "cardHolder": "Jane Doe"
}

# Eliminar tarjeta
DELETE http://127.0.0.1:3001/cards/1234567890123456
Authorization: Basic YWRtaW46YWRtaW4xMjM0